### PR TITLE
BUG: resolved version issue with java 8

### PR DESCRIPTION
**Pull request by sarmad1995**
This will solve the issue with java 8.
It happens on react-native 0.60 (Expo).

### CODE REVIEW

**Comment by mauron85** [comment]
Can you please remove commented lines all together? Git will do the job a tracking this change, so need to keep them. Thanks.

**Review by mauron85 — CHANGES_REQUESTED** [review]
Please remove commented lines. No need to keep them.

**Comment by sarmad1995** [comment]
@mauron85  When i try to make a release build with this.
There is an error I can't resolve. I tried a lot
`Program type already present: org.apache.commons.io.Charsets react native`,
I will try to solve both these issues at once, 
You also try to look into it as this is a major issue for new react native apps.

**Comment by teodorciuraru** [comment]
Wouldn't it be better to set the values from 1.6 => 1.7, instead of commenting?

Waiting for merge. Thank you!

**Comment by sarmad1995** [comment]
@teo029 Tried that. Didn't work though

**Pull request closed without merging**
