### PR TITLE
Feature/status 285

### PR DESCRIPTION
**Pull request by danielgindi**
Related to https://github.com/mauron85/react-native-background-geolocation/issues/270

https://github.com/mauron85/react-native-background-geolocation/pull/271

### CODE REVIEW

**Comment by mauron85** [comment]
Looking good, but please next time your PRs should be based on current master and not on the top of each other. Like this PR contains changes from https://github.com/mauron85/background-geolocation-android/pull/10. Should not be the case.

**Comment by mauron85** [comment]
The reason is obvious. With this PR you're forcing me to merge both PR 11 and 10. Not saying I'm not going to do that anyway, but I like to have a choice ;)

**Comment by danielgindi** [comment]
There were conflicts so I kept it based on the other PR...
But of course I could rebase before you merge if that's what you want!

**Comment by mauron85** [comment]
Ok. no problem.

**Comment by danielgindi** [comment]
I've rebased.
If merging with the other one, there will be a conflict in SyncAdapter, around these lines:
```
                if (isStatusOkay) {
                    builder.setContentText("Sync completed");
                } else {
                    builder.setContentText("Sync failed due server error");
                }
```

Those should be just wrapped in `if (builder != null) {`.

Btw I don't think we need the flavors for oreo and pre-oreo.
That SyncAdapter is mostly, like 99%, duplicated code.
It could be easily achieved with using either a one-line api version condition, or the support library which will just do nothing when referencing a notification channel.

**Comment by mauron85** [comment]
>Btw I don't think we need the flavors for oreo and pre-oreo.

The reason is react-native by default creates new project with pre oreo sdk.

**Comment by danielgindi** [comment]
Oh so the NotificationChannel does not exist at all right?
Btw I think they bumped the default sdk version in 0.57
https://github.com/react-native-community/react-native-releases/blob/0.57/CHANGELOG.md (targetSdkVersion is 26)

**Comment by mauron85** [comment]
If so, flavors can be removed. I was never actually fan, but it was just from necessity.

**Comment by danielgindi** [comment]
Yes I got it... If there only were `#define`s in Java/Kotlin...

**Comment by mauron85** [comment]
Merged. Thank you!

**Pull request closed without merging**
